// Configurations - Constants, etc.

module.exports =  {
  SERVICE_PORT    :33344,
  SERVICE_NAME    :"",
  CONTENT_SIZE		:  "CONTENT_SIZE",
  FLAG_PROB		    :  "FLAG_PROB",
  HIGH_PRIORITY	  :  "HIGH_PRIORITY",
  ATTACHMENT_PROB	:  "ATTACHMENT_PROB",
  INLINE_IMG_PROB	:  "INLINE_IMG_PROB",
  SUBJECT 			  :  "SUBJECT",
  DELIVERY 		    :  "DELIVERY",
  READCONFIRM 		:  "READCONFIRM",
  HTMLCODE 		    :  "HTMLCODE",
  LINKS			      :  "LINKS",
  COLOR			      :  "COLOR",
  COMPLETED		    :  "COMPLETED",
  REMINDER			  :  "REMINDER",
  FIRSTNAME		    :  "FIRSTNAME",
  LASTNAME			  :  "LASTNAME",
  MIDDLENAME		  :  "MIDDLENAME",
  NICKNAME			  :  "NICKNAME",
  WEBSITE			    :  "WEBSITE",
  COMPANY			    :  "COMPANY",
  JOBTITLE			  :  "JOBTITLE",
  IMADDRESS	  	  :  "IMADDRESS",
  BIRTHDAY			  :  "BIRTHDAY",
  DEPARTMENT		  :  "DEPARTMENT",
  MANAGER			    :  "MANAGER",
  EMAIL_COUNT		  :  "EMAIL_COUNT",
  PHONE_COUNT		  :  "PHONE_COUNT",
  ADDRESS_COUNT	  :  "ADDRESS_COUNT",
  AVATAR			    :  "AVATAR",
  LOCATION			  :  "LOCATION",
  LABEL			      :  "LABEL",
  SHOWAS			    :  "SHOWAS",
  RESOURCE			  :  "RESOURCE",
  PRIVATE			    :  "PRIVATE",
  ALL_DAY			    :  "ALL_DAY",
  PAST_EVENTS		  :  "PAST_EVENTS",
  RECURRENCE		  :  "RECURRENCE",
  ATTENDEES		    :  "ATTENDEES",
  PASSWORD		 	  :  "PASSWORD",
  DESCRIPTION		  :  "DESCRIPTION",
  FULLNAME			  :  "FULLNAME",
  EMAIL_CC        :  "EMAIL_CC",

  PAGE_INDEX      : "index",
  PAGE_ACCOUNTGEN : "accountgen",
  PAGE_EMAILGEN   : "emailgen",
  PAGE_EVENTGEN   : "eventgen",
  PAGE_CONTACTGEN : "contactgen",
  PAGE_TASKGEN    : "taskgen",
  PAGE_NOTEGEN    : "notegen"
};
